#!/bin/bash
# RIS INTEGRATION CHECKLIST
# Version: 3.0, Date: March 17, 2026
# Usage: Print this file and check off items as completed

echo "=================================="
echo "RIS INTEGRATION CHECKLIST"
echo "=================================="
echo ""
echo "📋 PRE-INTEGRATION SETUP"
echo "=================================="
echo "[ ] Read RIS_IMPLEMENTATION_SUMMARY.md"
echo "[ ] Open RIS_INTEGRATION_GUIDE.html in browser"
echo "[ ] Backup existing database"
echo "[ ] Stop DMW server (npm stop or Ctrl+C)"
echo ""

echo "🗄️  STEP 1: DATABASE MIGRATION"
echo "=================================="
echo "[ ] Locate: server/database/migration_ris_transactions_v3.sql"
echo "[ ] Open PostgreSQL terminal/GUI"
echo "[ ] Execute migration SQL file"
echo "[ ] Verify tables created:"
echo "    [ ] SELECT * FROM ris_notifications LIMIT 0;"
echo "    [ ] SELECT * FROM ris_approvals LIMIT 0;"
echo "    [ ] SELECT * FROM ris_status_history LIMIT 0;"
echo ""

echo "🔌 STEP 2: BACKEND API INTEGRATION"
echo "=================================="
echo "[ ] Locate: server/ris-endpoints-v3.js"
echo "[ ] Open: server/server.js"
echo "[ ] At top of server.js, add:"
echo "    const risEndpoints = require('./ris-endpoints-v3');"
echo "[ ] In app initialization, add:"
echo "    risEndpoints(app, pool, broadcastNotification);"
echo "[ ] Verify pool and authenticateToken are available"
echo "[ ] Check for syntax errors (npm test or node lint)"
echo ""

echo "🎨 STEP 3: FRONTEND HTML & CSS"
echo "=================================="
echo "[ ] Copy content from: renderer/ris-form-v3.html"
echo "[ ] Paste into: renderer/index.html (in main content area)"
echo "[ ] Add CSS link in <head> section of index.html:"
echo "    <link rel=\"stylesheet\" href=\"/renderer/styles/ris-styles-v3.css\">"
echo "[ ] Verify all modal IDs are unique in index.html"
echo "[ ] Check for HTML syntax errors (F12 -> Elements)"
echo ""

echo "💻 STEP 4: FRONTEND JAVASCRIPT"
echo "=================================="
echo "[ ] Add script reference before </body> in index.html:"
echo "    <script src=\"/renderer/scripts/ris-functions-v3.js\"></script>"
echo "[ ] Add initialization code in app.js:"
echo "    initializeRISModule();"
echo "[ ] Add navigation button to access RIS section"
echo "[ ] Verify no console errors (F12 -> Console)"
echo ""

echo "🧪 STEP 5: INITIAL TESTING"
echo "=================================="
echo "[ ] Start DMW server: npm start"
echo "[ ] Wait for server to fully start"
echo "[ ] Open application in browser"
echo "[ ] Check browser console for errors (F12)"
echo "[ ] Look for RIS section in navigation"
echo "[ ] Test loading RIS list (should show empty or existing RIS)"
echo ""

echo "✅ STEP 6: FUNCTIONAL TESTING"
echo "=================================="
echo "[ ] Test 1: Create RIS with catalog item"
echo "    [ ] Click 'New RIS' button"
echo "    [ ] Fill in Division, Office, Date, Purpose"
echo "    [ ] Click 'Add from Catalog'"
echo "    [ ] Select an item"
echo "    [ ] Click 'Create RIS'"
echo "    [ ] Check RIS appears in list with PENDING status"
echo "[ ] Test 2: Create RIS with manual item"
echo "    [ ] Click 'New RIS' button"
echo "    [ ] Click 'Add Manually'"
echo "    [ ] Enter: Description, Unit, Quantity"
echo "    [ ] Click 'Create RIS'"
echo "    [ ] Verify manual item in items table"
echo "[ ] Test 3: Manual item auto-catalog"
echo "    [ ] Wait 2-3 seconds"
echo "    [ ] In browser console run:"
echo "        fetch('/api/items').then(r=>r.json()).then(console.log)"
echo "    [ ] Verify manual item appears in items list"
echo "[ ] Test 4: Role-based visibility"
echo "    [ ] Check database: SELECT * FROM ris_notifications WHERE ris_id = X;"
echo "    [ ] Should show 6 roles: HOPE, BAC_SEC, BUDGET, CHIEF_FAD, ADMIN, SUPPLY_OFFICER"
echo "[ ] Test 5: Approval workflow"
echo "    [ ] Login as user with SUPPLY_OFFICER role"
echo "    [ ] View the RIS created earlier"
echo "    [ ] Click 'Approve RIS' button"
echo "    [ ] Verify status changes to APPROVED"
echo "    [ ] Check approvals table: SELECT * FROM ris_approvals WHERE ris_id = X;"
echo "[ ] Test 6: Print template"
echo "    [ ] Open an APPROVED RIS"
echo "    [ ] Click 'Print Template' button"
echo "    [ ] Verify print dialog opens"
echo "    [ ] Verify all info is formatted correctly"
echo ""

echo "📄 STEP 7: SAMPLE RIS VALIDATION"
echo "=================================="
echo "[ ] Test WRSD RIS - Alcohol 500mL"
echo "[ ] Test ORD RIS - Molding Tape"
echo "[ ] Test PROTECTION RIS - Multiple Items (3+)"
echo "[ ] Test ORD RIS - Customized Stamp (manual item)"
echo "[ ] Test ORD RIS - Multiple Supplies (5+ items)"
echo "[ ] Test WRSD RIS - HUDYAKA 2025 (priority flag)"
echo ""

echo "🔍 STEP 8: VERIFICATION"
echo "=================================="
echo "[ ] All 10 API endpoints respond (test with curl or Postman)"
echo "[ ] All functions in browser console (type function name)"
echo "[ ] Socket.IO notifications broadcast (if enabled)"
echo "[ ] Database has no errors in logs"
echo "[ ] No 404 or 500 errors in server console"
echo "[ ] All stakeholder roles can see their RIS"
echo "[ ] Supply Officer approvals are tracked correctly"
echo ""

echo "📚 STEP 9: DOCUMENTATION & TRAINING"
echo "=================================="
echo "[ ] Document how to create RIS"
echo "[ ] Document how to approve RIS (Supply Officer)"
echo "[ ] Document how to print template"
echo "[ ] Train end users on the system"
echo "[ ] Train Supply Officer on approvals"
echo "[ ] Create quick reference guide for users"
echo ""

echo "🚀 STEP 10: PRODUCTION DEPLOYMENT"
echo "=================================="
echo "[ ] All tests passed"
echo "[ ] No critical errors in logs"
echo "[ ] Database backup successful"
echo "[ ] Stakeholders notified of new feature"
echo "[ ] Monitor system for issues first 24 hours"
echo "[ ] Collect user feedback"
echo "[ ] Document any issues/enhancements"
echo ""

echo "=================================="
echo "✅ INTEGRATION COMPLETE!"
echo "=================================="
echo ""
echo "Files created:"
echo "  1. server/database/migration_ris_transactions_v3.sql"
echo "  2. server/ris-endpoints-v3.js"
echo "  3. renderer/ris-form-v3.html"
echo "  4. renderer/scripts/ris-functions-v3.js"
echo "  5. renderer/styles/ris-styles-v3.css"
echo ""
echo "Support documents:"
echo "  - RIS_INTEGRATION_GUIDE.html (open in browser)"
echo "  - RIS_IMPLEMENTATION_SUMMARY.md (read in editor)"
echo ""
echo "Next: Follow the 10 steps above to integrate and test."
echo ""
